### PR TITLE
Add database config operations

### PR DESCRIPTION
**Pull request by bentranter**
Adds the database config operations. Related to https://github.com/digitalocean/openapi/pull/571.

### CODE REVIEW

**Comment by bentranter** [comment]
Also pinging @rpmoore for review, the GitHub reviewers tab won't show that account for some reason

**Comment by bentranter** [comment]
!deploy

**Comment by scotchneat** [comment]
@bentranter / @rpmoore this change looks good to me but when I test the patch endpoint with the following payload (against a MySQL  db).

```
{"config":{"sql_require_primary_key": false}}
```

 I get:

```
{
    "id": "bad_request",
    "message": "the mask must be set with which fields are being updated",
    "request_id": "<request-id>"
}
```

**Comment by bentranter** [comment]
!deploy

**Comment by bentranter** [comment]
Link to `get` and `patch` database config operations https://api-engineering.nyc3.digitaloceanspaces.com/spec-ci/redoc-index.html?pr=583#operation/get_database_config

**Comment by shabtaisharon** [comment]
👋🏽 @scotchneat Currently we get & return the payload in a flat struct and we need to update that to be wrapped in a config object.
I have a jira for that and i'll work on fixing that.
I'll reply here once i have that fixed.
BTW, i'm working on adding Postgres & Redis to the get/set advanced config

**Comment by shabtaisharon** [comment]
My PR was merged and the changes are deployed to stage2 and production.
You should be able to PATCH mysql&postgres&redis now using that api

**Comment by andrewsomething** [comment]
This was implemented in https://github.com/digitalocean/openapi/pull/590

**Pull request closed without merging**
