### PR TITLE
Resolve openapi-generator 5.0.0 errors - new_volume_ext4 errors.

### PR DESCRIPTION
**Pull request by danaelhe**
Resolving errors with openapi-generator 5.0.0

When inputting the DO openapi spec into the latest release of openapi-generator, I would get an exception with new_volume_ext4 and new_volume_xfs (a "filesystem_type" needs to be required and a type of string")
    
Solution: include discriminator in the base schema (volume_write_file_system_type).
    
This resolved the exceptions.
    
With this PR, the DO spec is accepted into the latest version of openapi-generator (5.0.0) exception/error free and is able to generate a python client.

### CODE REVIEW

**Review by ChiefMateStarbuck — APPROVED** [review]
NICE

**Comment by danaelhe** [comment]
> NICE

thanks sam!! always appreciate your enthusiasm :D

**Comment by danaelhe** [comment]
@andrewsomething I think i need to add an example to floating_ip_actions.yml for type- what would be an appropriate example for that attribute?

**Comment by andrewsomething** [comment]
@danaelhe Looks like it needs a merge/rebase on main to clean up the diff.

>  I think i need to add an example to floating_ip_actions.yml for type- what would be an appropriate example for that attribute?

The only valid values are the ones described in the discriminator: `assign` and `unassign`

**Comment by danaelhe** [comment]
> @danaelhe Looks like it needs a merge/rebase on main to clean up the diff.
> 
> > I think i need to add an example to floating_ip_actions.yml for type- what would be an appropriate example for that attribute?
> 
> The only valid values are the ones described in the discriminator: `assign` and `unassign`

What makes you say that? It appears "This branch has no conflicts with the base branch"

**Comment by andrewsomething** [comment]
Look at the "Files changed" tab. It includes changes from your previous floating IPs PR. It makes it difficult to review. In a glance, it is hard to tell if there are actually new floating IP related changes here.

**Comment by danaelhe** [comment]
rebasing in another pr

**Pull request closed without merging**
