### PR TITLE
Break lines for cURL examples.

### PR DESCRIPTION
**Pull request by andrewsomething**
```
grep -rl '\-H "Content-Type:' specification/*/*/examples/curl | xargs sed -i 's/-H "Content/\\\n    -H "Content/g'
grep -rl '\-H "Authorization:' specification/*/*/examples/curl | xargs sed -i 's/-H "Authorization/\\\n    -H "Authorization/g'
grep -rl "\-d '{" specification/*/*/examples/curl | xargs sed -i 's/-d/\\\n    -d/g'
grep -rl '"https://api' specification/*/*/examples/curl | xargs sed -i 's|"https://api|\\\n    "https://api|g'
```

### CODE REVIEW

**Comment by dbrian57** [comment]
!deploy

**Comment by scotchneat** [comment]
!deploy

**Comment by scotchneat** [comment]
@dbrian57 It looks like your `deploy` comment didn't trigger because your visibility in the digitalocean org is set to `Private`. See [here](https://github.com/orgs/digitalocean/people?query=dbrian57).

**Review by scotchneat — APPROVED** [review]
:shipit:

**Pull request merged**
