### PR TITLE
APPS-7813 Add autoscaling section to apps

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title.

### CODE REVIEW

**Review by mavis1007 — APPROVED** [review]

**Review by andrewsomething — COMMENTED** [review]
As this is not accessible to all customers yet, do we want to label this as beta somehow?

**Comment by markusthoemmes** [comment]
Closing this for now. Will bring it back when we're going GA with it.

**Comment by markusthoemmes** [comment]
Reopened this as it's becoming relevant again. Rollout is at 3%.

**Review by andrewsomething — APPROVED** [review]
:+1:  LGTM!

**Pull request merged**
