### PR TITLE
Update eviction policies to include details on each enum option

### PR DESCRIPTION
**Pull request by DWizGuy58**
**What**

- Updates eviction policies for `Configure the Eviction Policy for a Redis Cluster` and `Update the Database Configuration for an Existing Database` (Redis) to include details on each eviction policy

**Why**

- Provides more details on how each eviction policy works

**Evidence**

image

image

image

### CODE REVIEW

**Review by rpmoore — DISMISSED** [review]

**Comment by shabtaisharon** [comment]
!deploy

**Review by ChiefMateStarbuck — APPROVED** [review]
!deploy

**Review by ChiefMateStarbuck — CHANGES_REQUESTED** [review]
error on lint. you can run `make lint` to run the linter locally.

**Comment by DWizGuy58** [comment]
will address and push an update

**Comment by DWizGuy58** [comment]
Fixed small issue with GET request on retrieving eviction policy, ensured parity with current doc format.

https://github.com/digitalocean/openapi/pull/705/files#diff-1600bfed3244d31364057a19855e6bc6e572f1b72373bc9dae59ea3dbee9024b

**Review by ChiefMateStarbuck — APPROVED** [review]
!deploy

**Review by ChiefMateStarbuck — COMMENTED** [review]
!deploy

**Comment by scotchneat** [comment]
!deploy

**Review by scotchneat — COMMENTED** [review]
!deploy

**Comment by ChiefMateStarbuck** [comment]
Github might be having issues. We're gonna give it some time and attempt to generate a preview later.

**Pull request merged**
